version: "3"

services:
  web:
    container_name: mmdb_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 5000:5000
    environment:
      - MMDB_APP_SECRET=${MMDB_APP_SECRET}
      - MMDB_APP_REDIS_URL=mmdb_redis
      - MMDB_APP_REDIS_PORT=6379
      - MMDB_APP_DB_HOST=mmdb_postgres
      - MMDB_APP_DEV_DB_NAME=${MMDB_DEV_DB_NAME}
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: mmdb_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${MMDB_USER}
      - POSTGRES_DB=${MMDB_DEV_DB_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    container_name: mmdb_redis
    image: redis:latest
    ports:
      - 6379:6379